# Site settings
title: Gust Tech Blog 
email: your-email@domain.com
description: Gust is a platform that connects early stage entrepreneurs and angel investors.  This is the blog of the developers who work on builiding the platform
baseurl: ""
url: "http://gust.com"

# Build settings
markdown: kramdown
permalink: pretty
